//try block without catch --gives error
//throw without catch--abnormally terminate the program or show error
#include<iostream>
using namespace std;
int main(){
    try{
        throw 10;
    }
}